### ISSUE TITLE
Wrong schema shows the cathode connected through a resistor.

### ISSUE THREAD

**Issue by fraufalke** [sunfounder/3in1-kit#2]
hi!
I apologize if I'm wrong, but the description says that the anode needs to be connected to the GPIO pin through a resistor and the cathode needs to be connected to the GND pin. While image shows the opposite.

![Знімок екрана 2023-10-15 о 19 31 36](https://github.com/sunfounder/3in1-kit/assets/49170138/b9611b62-91a7-43d2-981e-e563a559d1ec)

relevant file: https://github.com/sunfounder/3in1-kit/blob/docs-r3-en/docs/source/arduino_start/basic_circuit.rst

**Comment by eMUQI** [comment]
Thank you for your feedback! This diagram is provided as an example of incorrect linking practices, demonstrating what should be avoided. For more details, please refer to the following link:

https://github.com/sunfounder/3in1-kit/blob/bb049289ffe14f778ef38dec0f48a5fce1e7ed7e/docs/source/arduino_start/basic_circuit.rst?plain=1#L87-L97
